### ISSUE TITLE
Generation issue.

### ISSUE THREAD

**Issue by SofeyKujo** [Vali-98/ChatterUI#1]
While using mancer, it always sends stuff unrelated to the character, and almost always sends a wrong reply to basic stuff like hi. 
Good work, tho. It's nice and easy to use but it just needs some tinkering
![Screenshot_2023-11-05-17-36-08-228_com Vali98 ChatterUI-edit](https://github.com/Vali-98/ChatterUI/assets/92738404/6c99340d-e569-40fe-80a3-670eccb20ed6)

**Comment by Vali-98** [comment]
Hi, could you provide details on:
- What version of ChatterUI you are running.
- What mancer model was used.

Testing on v0.4 seems fine on my part.

**Comment by SofeyKujo** [comment]
> Hi, could you provide details on:
> 
> * What version of ChatterUI you are running.
> * What mancer model was used.
> * Presets used.
> 
> Testing on v0.4 seems fine on my part.


I'm using latest release, with mytholite

**Comment by SofeyKujo** [comment]
Nvm i closed it by mistake lol

**Comment by SofeyKujo** [comment]
I meant this version. 
![Screenshot_2023-11-07-12-38-45-247_com kiwibrowser browser-edit](https://github.com/Vali-98/ChatterUI/assets/92738404/6e4e40c1-e9b1-4776-9072-19f8acb473e9)

And as for the issue, it happens with all characters. It just speaks as user, or speaks completely out of the subject or says random stuff that have no meaning at all

**Comment by Vali-98** [comment]
Could you contact me on discord / email for further discussion? I am still not able to replicate your issue.

**Comment by SofeyKujo** [comment]
My discord username is @ricardo.milos69 feel free to send a request or dm and I'll reply asap
