### ISSUE TITLE
OpenRouter problems: No reply at all or after a few minutes 

### ISSUE THREAD

**Issue by CyborgArmy83** [Vali-98/ChatterUI#105]
![l0g](https://github.com/user-attachments/assets/b55fe647-bc0d-4488-906c-06b2c9400bcd)
I recently re-downloaded the app and tried it out on my Android phone. It seems like OpenRouter has some problems. 

I selected my default model (hermes-405:free) and API key but it is not streaming a response. I have plenty of credits and it's working on other apps. Most often I get an empty screen as output or it will output something small after 70-90 seconds. Not sure if it related to a (broken?) model selection. Can you also add a model in the top of the list called "user default" to choose whatever you made standard in the OpenRouter settings? I'm looking forward to hear if others are facing similar issues and what can be done about it. I am using A15 and the latest app release (0.8.1)

Update 1: Okay, after more testing it seems that there are quite a few models in the list that do not work in the way I would figure, such as the 405 hermes one. If I select Sonnet 3.5 it works most of the time. Not sure if the list is hardcoded and might contain some errors either in the naming or calling the models. 

Update 2: It could also be an API / server problem on their side. Not pointing fingers, just trying to figure it out!

May I also suggest a model search / type field in the openrouter API settings? This would be 1000% appreciated :)

**Comment by Vali-98** [comment]
Hey there, thanks for the feedback!

> Not sure if the list is hardcoded and might contain some errors either in the naming or calling the models.

Its obtained directly from OpenRouter, so it should be 100% accurate, unless OpenRouter themselves are screwing up something.

> May I also suggest a model search / type field in the openrouter API settings? This would be 1000% appreciated :)

This is one of the additions planned for an upcoming API-rework.

**Comment by Vali-98** [comment]
> May I also suggest a model search / type field in the openrouter API settings? This would be 1000% appreciated :)

This has been added to the beta build with the new API Manager.
