### ISSUE TITLE
Show model file name

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#106]
It seems like the shown name now comes directly from the gguf. Some related models can show the same name (if one is a merge of the other). While I like the info from the gguf and would like if we keep that, I would also like to see the actual file name in addition to that. The file name was shown before the gui rework.

**Comment by Vali-98** [comment]
I decided to redo a bit of the external model logic to get this working, Ideally model authors would also modify the internal names on quantization but I understand this isnt always the case. I think the full filenames are often too long, so a small compromise would be to have them as a smaller element:

![image](https://github.com/user-attachments/assets/1ace276f-f8e1-4ce7-b9f3-e198c172a972)

This should be usable, perhaps a future feature would be to make this information collapsable/ expandable.
