### ISSUE TITLE
Resend request on empty response / Add gemini experimental models

### ISSUE THREAD

**Issue by chitudorin** [Vali-98/ChatterUI#109]
Google's Gemini experimental models are available on OpenRouter, but they're quickly reaching rate limit and returning an empty response. It would be nice to have an option to resend request on empty response for this cases, instead of manually clicking resend. 

Apart from that, it would be cool to have those providers (Google Vertex and AI Studio) available in the app, because those models are free and quite capable.

https://openrouter.ai/google/gemini-pro-1.5-exp

**Comment by chitudorin** [comment]
Seems like this problem happens only on Google AI Studio, not on Vertex. Perhaps there could be a "provider" dropdown for OpenRouter in the future.

**Comment by Vali-98** [comment]
I think I'll close up this issue as:

1. The API rework is in the works
2. The retry function will likely not be added
