### ISSUE TITLE
There is a problem with markdown unordered list rendering.

### ISSUE THREAD

**Issue by GeminiX369** [Vali-98/ChatterUI#111]
Markdown's unordered list will be rendered as an ordered list, which will continue and increase the sequence number of the ordered list.
It is recommended to use the open source Markdown rendering library, there is no need to write it yourself. The markdown rendering written by myself has imperfect functions, it doesn't look pretty either, and will be difficult to maintain in the future.

**Comment by Vali-98** [comment]
> It is recommended to use the open source Markdown rendering library

ChatterUI currently uses a slightly modified version of:
https://github.com/andangrd/react-native-markdown-package

The Markdown definitions in app/constants/Markdown.ts are for styling.

Could you provide an example text that causes this issue?

**Comment by GeminiX369** [comment]
> > It is recommended to use the open source Markdown rendering library
> 
> ChatterUI currently uses a slightly modified version of: https://github.com/andangrd/react-native-markdown-package
> 
> The Markdown definitions in app/constants/Markdown.ts are for styling.
> 
> Could you provide an example text that causes this issue? As far as I've tested, unordered lists should always have correct bullet points:
> 
> ![image](https://private-user-images.githubusercontent.com/137794480/384860020-bccbd066-a650-4169-8bff-a774ebb61842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODQyMjUsIm5iZiI6MTczMTM4MzkyNSwicGF0aCI6Ii8xMzc3OTQ0ODAvMzg0ODYwMDIwLWJjY2JkMDY2LWE2NTAtNDE2OS04YmZmLWE3NzRlYmI2MTg0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMzU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjA0MWNjYzljNmY3NDJjNzJiYjliZTdlMTUwNWI4ZjI3NDRjODc1ZDkxMDE5NjY0OTRiZjU1NTAwOGIxZGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hu4NMl2GLP27ehAZZJBeqtksjqkq1PC98w0d17avCQ8)
> 
> Used text:
> 
> ```
> Hello! How can I help?
> - test1
> - test2
> 
> 1. test3
> 2. test4
> ```

Of course, for example:
```markdown
1. ordered list item1
- unordered list item a
- unordered list item b
- unordered list item c

2. ordered list item2
- unordered list item x
- unordered list item y
- unordered list item z

3. ordered list item3
```

**Comment by GeminiX369** [comment]
> Ive done a bit of digging and it seems that this is an issue with the current Markdown library used by ChatterUI having somewhat outdated markdown definitions. It wil only properly render a mix of ordered lists with unordered sublists when indented:
> 
> ```
> 1. ordered list item1
>     - unordered list item a
>     - unordered list item b
>     - unordered list item c
> 
> 2. ordered list item2
>     - unordered list item x
>     - unordered list item y
>     - unordered list item z
> 
> 3. ordered list item3
> ```
> 
> Interestingly , Github's markdown renderer does not have the same issue.
> 
> I will have to investigate other markdown renderers for a solution.

Sorry to trouble you, I've seen this problem many times in AI's replies.

**Comment by Vali-98** [comment]
Alright, with commit 704b0e50eaefd5f603db4d3d2c7ab2509eb9a7d3 , ChatterUI now uses [react-native-markdown-display](https://www.npmjs.com/package/react-native-markdown-display) which has a far better markdown parser and renderer. This fixes the initial issue with ordered and unordered lists.
