### ISSUE TITLE
Is Self-Extend supported?

### ISSUE THREAD

**Issue by lrq3000** [Vali-98/ChatterUI#117]
Is Self-Extend supported in ChatterUI's version of llama.cpp? If yes, could a setting to enable it be added? It could be extremely useful to extend the context window of small models, great for RAG and summarization on-device (it already works well IMHO with "Bypass Context Length", but it may work even better with Self-Extend).

See this discussion for context: https://www.reddit.com/r/LocalLLaMA/comments/1b1q88w/selfextend_works_amazingly_well_with_gemma2bit/

**Comment by Vali-98** [comment]
> Is Self-Extend supported in ChatterUI's version of llama.cpp? If yes, could a setting to enable it be added? 

To my surprise, yes, it does exist in llama.cpp:

https://github.com/ggerganov/llama.cpp/pull/4815

It currently isn't exposed by llama.rn, but that can be added.

> it already works well IMHO with "Bypass Context Length"

Just as a note, `Bypass Context Length` is not a modification to llama.cpp's context limits, it simply allows you to dangerously ignore context limits that may or may not actually work. As far as the internal llama.cpp is concerned, it still truncates the prompt to fit into the context window.

**Comment by lrq3000** [comment]
That would be incredible!

I read the sourcecode of how you implemented Bypass Context Length, indeed I would not think this could work, but it does with some models. I tested with phi-3.5-mini and it works surprisingly well. Of course, due to the limited context, it will hallucinate the responses to queries that pertain to older tokens, but still it allows it to function over huge inputs such as documents that should not be supported.

I think, but I'm not sure, that self-extend would be the perfect complementary method to avoid this loss of information. Here is a great technical dive on how self-extend works:

https://www.bluetickconsultants.com/blogs/beyond-boundaries-unleashing-longer-contexts-with-self-extend-in-llms.html

I'm going to try on desktop with llama.cpp to see if it's worth it, with the same content and models I test on mobile.

**Comment by lrq3000** [comment]
Also I would like to clarify that it's not just to work on documents. A bigger context would allow to conduct longer discussions sessions with longer running context. These long discussions are often extremely useful and happen for critical queries in my experience with ChatGPT, so having that on-device would be a huge leap forward and leagues above anything else in the mobile offline genAI apps ecosystem!

**Comment by lrq3000** [comment]
Also I don't know if it would be possible with llama.rn, but it would be an even more generic solution if we could have a textbox to pass arbitrary command line flags.

**Comment by lrq3000** [comment]
Oh I see, I only suggested to be able to pass any flags as I thought it would be easier for you, but then please scrap that if that's actually the opposite.

Awesomi that you know about self-extend, I didn't at all, I was surprised such a tech exists that can drastically extend the context size of any model at no cost! And it seems everybody else forgot about this tech too, as there were discussion to make it a default behavior in llama.cpp. Furthermore, most if not all desktop UI based on llama.cpp are not exposing self-extent either, very strange.

Then do you know if self-extend does not increase RAM usage significantly, or this is still a requirement?

**Comment by Vali-98** [comment]
After some deliberation, Self-Extend is probably not useful enough to use over more conventional context-extension strategies such as RoPE.

I will consider instead to add an automated RoPE calculation similar to the approach in KoboldCPP.
