### ISSUE TITLE
When can additional languages from other countries be added?

### ISSUE THREAD

**Issue by fvgfgtxdeujv** [Vali-98/ChatterUI#119]
I hope to add Simplified Chinese.

**Comment by Vali-98** [comment]
It is possible to add using [react-i18next](https://www.npmjs.com/package/react-i18next) to fully translate all screens, but this is not planned at the moment.

There is a fork which adds i18next, but only for Polish:
https://github.com/Mateusz-Dera/ChatterUI-Multilang

**Comment by fvgfgtxdeujv** [comment]
Thank you.

**Comment by fvgfgtxdeujv** [comment]
Can I create a configuration file to store the text of the application interface, making it easier for us to translate into the languages we need?

**Comment by Vali-98** [comment]
At the moment I don't plan on implementing this change to ChatterUI just yet, but yes preferably used some config file to translate all text.

**Comment by fvgfgtxdeujv** [comment]
Okay, thank you
