### ISSUE TITLE
Max context 

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#12]
According to Meta, Llama was trained with 8192 token sequences but the app only allows 8096 as max size for context. Is this intended or is this a limitation of llamacpp? Or should we not set it to 8192?

**Comment by Vali-98** [comment]
The max context size was increased to 32k in a3d3f3373ca3d63311698de40b5f6837a2b45423 and should be in 0.7.3.

**Comment by GameOverFlowChart** [comment]
@Vali-98 I just realized that you Said 0.7.2 I thought you were talking about a future version. I had 0.7.2 and the slider did not go higher. I updated to 0.7.3 and the issue is the same (Android by the way). And I just checked the min value is also wrong it's 32 for me but the code you have shown says it should be 1024.

By the way this app runs great on my device I used maid before but it's new versions don't work for me.

**Comment by Vali-98** [comment]
> @Vali-98 I just realized that you Said 0.7.2 I thought you were talking about a future version. I had 0.7.2 and the slider did not go higher. I updated to 0.7.3 and the issue is the same (Android by the way, not in an emulator or something). And I just checked the min value is also wrong it's 32 for me but the code you have shown says it should be 1024.
> 
> By the way this app runs great on my device I used maid before but it's new versions don't work for me.

I think I understand the issue, I was assuming you were speaking about sampler settings when instead this was an issue with the Local API max tokens settings. This will be updated.
