### ISSUE TITLE
[Feature] Make Ollama requests possible with API keys

### ISSUE THREAD

**Issue by short-circuit** [Vali-98/ChatterUI#121]
I am running my Ollama on a webserver behind authentication with API keys.
Is it possible to (optionally) add an input field for API keys when Ollama is selected so that the requests are made with bearer token?
The webserver running the Ollama server is [Openwebui](https://openwebui.com/).
Right now the requests won't go throught because the authentication is missing. Exposing Ollama to the internet unprotected is also not an option.

**Comment by Vali-98** [comment]
This is perhaps a goal to be added with the upcoming API rework. However, at the moment I've been blocked by the SDK update which is causing a few issues.

**Comment by Vali-98** [comment]
The latest beta adds API Configurations which could solve this: https://github.com/Vali-98/ChatterUI/discussions/126
