### ISSUE TITLE
bullet points within numbered lists are not formatted correctly

### ISSUE THREAD

**Issue by phly95** [Vali-98/ChatterUI#122]
The markdown formatting fails when given bullet points within numbered lists. Like: 

```
1. **Enhanced Privacy and Security**:
   - **Data Minimization**: By processing AI models locally, the amount of data that needs to be transmitted and stored is significantly reduced. This minimizes the risk of data breaches and unauthorized access.
   - **No Third-Party Access**: The AI models and their training data remain on the user's device, preventing any third-party entities from accessing or analyzing this sensitive information.
   ```

The word wrap doesn't trigger and it just keeps going off screen.

**Comment by Vali-98** [comment]
![image](https://github.com/user-attachments/assets/8c4e1894-7cfc-4a12-be50-d470eb76e509)

I believe this is fixed in beta builds, however it is not recommended to change to beta at the moment.
