### ISSUE TITLE
[Feature Request] Mistral AI api type? 

### ISSUE THREAD

**Issue by Xpolo29** [Vali-98/ChatterUI#124]
Hi sorry if duplicate but is it possible to add a Mistral AI api type? I would like to use Ministral 3B with this app. Thanks!

**Comment by Vali-98** [comment]
Hi, do you mean using Mistral's API service or running Ministral on mobile?

If the former, I think you can use Mistral's API via Chat Completions, just enter mistral's API as the target.

If the latter, it should already be able to run in local mode.

**Comment by Vali-98** [comment]
The latest beta adds API Configurations which could solve this too:
https://github.com/Vali-98/ChatterUI/discussions/126
