### ISSUE TITLE
Gemma shows special tokens.

### ISSUE THREAD

**Issue by Zibri** [Vali-98/ChatterUI#128]
Every message ends with:
`<end_of_turn><eos>`

**Comment by Vali-98** [comment]
Are you using the Gemma 2 Instruct format?

**Comment by Zibri** [comment]
Yep. Gemma 3 instruct

**Comment by Vali-98** [comment]
Does it have `<end_of_turn>` in its stop sequence?

**Comment by th1nhhdk** [comment]
For me, every message starts with `<eos>` and have broken newline

**Comment by Vali-98** [comment]
I think the issue is that the `output_prefix` and `last_output_prefix` are missing a newline. This can be updated for new installs, but for existing installations, will require you to enter the newlines manually. Sorry bout the issue!

If this doesn't fix it, feel free to reopen this.
