### ISSUE TITLE
Emojis broken

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#13]
I think this was introduced in the update from 0.7.2 to 0.7.3 but I'm not sure.
Emojis outputted by the model are shown as ??. But the things is the emojis are shown correctly in the log so it must be the chat gui which can't show them right. If I send emojis or put them in the greeting it's still shown correctly but if it comes from the model only the log screen shows them correctly.

**Comment by Vali-98** [comment]
Could you by chance send whatever emojis are broken? The ChatItem component uses https://github.com/andangrd/react-native-markdown-package to display in message. Also, check if its also broken in the Chat Edit menu.

So far, my tests show emojis to be working.

**Comment by GameOverFlowChart** [comment]
I will try to reproduce and give you the log later.

**Comment by GameOverFlowChart** [comment]
I can't reproduce, maybe it was the ai acting weird and I thought that I have seen stuff in the log that wasn't there? But as a reminder, this other problem still exists for me: https://github.com/Vali-98/ChatterUI/issues/12#issuecomment-2081103279

I also had once the problem that the text did overflow to the right so that I couldn't read the rest maybe it was linked to this but I can't reproduce that either so I'm closing this.
