### ISSUE TITLE
Please add support for LM Studio

### ISSUE THREAD

**Issue by TUBii** [Vali-98/ChatterUI#130]
Really love your app. I'm only missing an LM Studio integration. It has OpenAI API like backend so it is easy to integrate. Just needed to add an option like Ollama, but with adjusted backend. 
LM Studio is really easy to use for the users and it can be ran as a server with a press of a button and serving it in the local network. 
It would be so nice to have this function in your app. Thanks.

**Comment by Vali-98** [comment]
Have you tested if this works with the generic Text Completions or Chat Completions APIs?

**Comment by ArchEngel0** [comment]
LM Studio definitely works!
Set API Type to Chat Completions
Leave API Key blank
Put in your endpoint - ipaddress:port/v1
 - /v1 is needed
then hit test, should work, and you can even pick the model you would like to use.

**Comment by Vali-98** [comment]
Thanks for testing! I'll assume this can be closed then, as the Chat Completions endpoint serves as a compatible OAI style connection.
