### ISSUE TITLE
Problem with the accuracy of generated response!

### ISSUE THREAD

**Issue by OpinionMatter** [Vali-98/ChatterUI#131]
I use the phi3 model developed by Microsoft locally to answer multiple choice questions with an accuracy of upto 90%, however after you've added new parameters to the sampler settings such as XTC probability and XTC threshold the accuracy of the answers has dropped significantly.

Perhaps you could share with us the optimum values of the such parameters to get the highest reponse accuracy or enlighten us on what other changes have been done to the app that might explain the inaccuracy in the v0.8.3-beta4 most recent update.

P.S.
The version that gave me better accuracy in the responses was v0.7.10 and all the answers are verified using a reliable question bank containing the multiple choice questions and their answers.

**Comment by Vali-98** [comment]
Have you tested this with identical seed values? I do not recall any regression after these changes.

**Comment by OpinionMatter** [comment]
> Have you tested this with identical seed values? I do not recall any regression after these changes.

Yes I've tested it with identical seed values and the accuracy of the generated responses dropped from 90% on (v0.7.10) to less than 79% on (v0.8.3-beta4) ever since the new parameters such as Tail-Free Sampling, XTC probability and XTC threshold were added to the sampler settings.

**Comment by Vali-98** [comment]
Did you properly disable these samplers? They should be disabled by default. XTC specifically is designed for creativity, not accuracy.

**Comment by Vali-98** [comment]
I will be closing this issue for now, as it doesn't seem like much has changed under the hood aside direct lcpp engine changes. Let me know if this continues to be an issue.
