### ISSUE TITLE
Update. Temperature slider

### ISSUE THREAD

**Issue by bi4key** [Vali-98/ChatterUI#133]
Menu -> Sampler -> Samplers

Temperature slider, why Temperature range in so big from 0-10 when normal use is about 0.2 to 1.0. 

And when range is so big is hard set up smaller range like 0.2 because slider is out of precise when set up manualy.

When slider will be smaller range example 0-2 or 0-3 then precision to set up new value will be better.

**Comment by Vali-98** [comment]
The issue with the Temperature is that some models can have usable temps with high values. That said, perhaps it can be lowered to 3, as I don't see many people using values above 2.
