### ISSUE TITLE
New. Add new section on menu "Character"

### ISSUE THREAD

**Issue by bi4key** [Vali-98/ChatterUI#136]
Add to left hamburger menu section Character:
Character
Sampler
Instruct

Menu and GUI will be more user friendly (intuitive). 

Because now when user is on section Chat he must on Android bottom navigation use back to jump to character section.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the SettingsDrawer.tsx file to include new menu items for Character, Sampler, and Instruct sections. This will improve navigation and make the GUI more user-friendly and intuitive.

You can review changes in this commit: https://github.com/mnmnk43434/Vali-98-ChatterUI-136/commit/9c2f75c075fc9a70ed2ef6a398073896f4547917.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Vali-98** [comment]
The primary issue about this is that the Character List and Chat states are not directly linked to the drawer. I do not believe this is easy to implement.

At the moment, the manual method of going back to the Character list is Triple Dot -> Main Menu

This change is not being considered, sorry.
