### ISSUE TITLE
New. Add sort option to models

### ISSUE THREAD

**Issue by bi4key** [Vali-98/ChatterUI#137]
Menu -> Models 

Add sort options, when user will have more models z this will help to organize models:

Section of sorting:
Name of model
Model group (Llama, Gemma, etc)
Default by Name

**Comment by Vali-98** [comment]
Is this actually needed? Models are several gigabytes each, and I don't think many users have more than 5-6 models installed at a time.

**Comment by bi4key** [comment]
> Is this actually needed? Models are several gigabytes each, and I don't think many users have more than 5-6 models installed at a time.

Maybe you are right, in normal use it will be ok.

Now I test many models and have many of them, and this idea jump to my head.

**Comment by Vali-98** [comment]
I do not think I will be implementing this, sorry!
