### ISSUE TITLE
Cant load model on android

### ISSUE THREAD

**Issue by danemadsen** [Vali-98/ChatterUI#14]
No permission was requested so I suspect its an android permissions issue.

Using v0.7.3 on android 14.

**Comment by Vali-98** [comment]
Hey there, I require some more information:
- The model loaded.
- What were the steps that led to this issue.
- Any relevant logs.
Thanks for your time.

**Comment by GameOverFlowChart** [comment]
Just want to add that it works on Android 13 so it might be Android 14 specific? 
No permissions seems to be right since you use the file picker of Android, there is no permission needed if the user himself picks the file that way, that's actually a good thing.

**Comment by danemadsen** [comment]
NVM i selected the Load button when i should have selected the import model button

**Comment by danemadsen** [comment]
Cool app, I just wanted to use it to see why maid is so slow though
