### ISSUE TITLE
OpenAI like compatible API support

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Vali-98/ChatterUI#140]
Recently got to know of this project. For such a good project, OpenAI like compatible API support is a miss

**Comment by howdoiusekeyboard** [comment]
Option to add custom API host by changing the base URL

**Comment by howdoiusekeyboard** [comment]
Found the workaround through chat completions.

**Comment by Vali-98** [comment]
Hey there, just for reference Chat Completions is the intended solution for OpenAI-compatible endpoints.
