### ISSUE TITLE
[Bug] ChatterUI v0.8.3 - Samplers Bug

### ISSUE THREAD

**Issue by bi4key** [Vali-98/ChatterUI#151]
[Bug] ChatterUI v0.8.3 - Samplers Bug

Samplers in sliders changed, but in value box the value label don't change

I try delete all, and create from default.

And look like:
if I create new preset 
then new on was created 
and copy all old value 
and this value stay

---

0.2 
![Screenshot_20241223-182751](https://github.com/user-attachments/assets/e9019c8a-9843-4e6e-bd9b-4c09e95ed98f)

---

0.7

![Screenshot_20241223-182815_1](https://github.com/user-attachments/assets/dff1d49a-1f3a-4345-966f-178a1ff5cebe)

---

![Screenshot_20241223-182922_1](https://github.com/user-attachments/assets/0a7e7730-68d5-4baf-b4b0-137eb87f2ae4)

**Comment by Vali-98** [comment]
It seems that SliderInput did not consider the case where the parent updates the value without updating the child, this has been fixed in cd1e47a257cdb20659d898a3b523a2892dd30d71
