### ISSUE TITLE
Apk release with latest llamacpp

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#17]
Could we get a new apk release with the latest llamacpp? Llamacpp is evolving fast, and as far as I understand it got a few fixes during the last days which are related to llama 3.

**Comment by Vali-98** [comment]
It would be ideal to always be on the latest version, but this project relies entirely on the llama.rn:
https://github.com/mybigday/llama.rn

I do not have the resources to upkeep a fork for the project with latest llama.cpp build, so I will leave it up to the llama.rn maintainer.

**Comment by GameOverFlowChart** [comment]
Oh I see yes, in retrospect I should know that. Their last release seems to be from last week.
