### ISSUE TITLE
llava Support

### ISSUE THREAD

**Issue by MrGGLS** [Vali-98/ChatterUI#18]
Hey there, this project rocks! I saw the multimodal version of Phi-3 on Hugging Face. Does this project currently support it now?
https://huggingface.co/xtuner/llava-phi-3-mini-gguf

**Comment by Vali-98** [comment]
Hey, thanks for using the app!

Technically this would 'work' in llama.cpp, however the app lacks any method of passing images to the model at the moment, and I believe the feature is also missing from llama.rn that this project relies on.

If you meant passing images to a multimodal backend, then it also isn't possible as there is no functionality in place to attach images to messages just yet.  This will likely not be added soon, sorry
