### ISSUE TITLE
App crashes on loading local model.

### ISSUE THREAD

**Issue by Dhruvanand24** [Vali-98/ChatterUI#20]
Using StableLm-2-zephyr-1_6b-q1_1.gguf 6gb ram android 11.

**Comment by Vali-98** [comment]
Can you provide a link to the model file used?

**Comment by Dhruvanand24** [comment]
https://huggingface.co/Crataco/stablelm-2-1_6b-chat-imatrix-GGUF/blob/main/stablelm-2-1_6b-chat.Q4_K_M.imx.gguf

**Comment by Vali-98** [comment]
It seems to be attempting to access memory outside its buffer, likely a llama.rn issue.

**Comment by Dhruvanand24** [comment]
okay, are you sending the whole conversation history as a prompt or just the current message?

**Comment by Vali-98** [comment]
The app fills the context with the latest message history until the context limit is filled.

**Comment by Dhruvanand24** [comment]
So I have a similar type of app where I append all the previous prompts and model responses along with the new prompt for it to remember the past converstations. If I only send the current prompt, It seems to not remeber anything of the past converstation.
The downside is, response generation starts a bit slow when I send the whole conversation history each time. Am I doing something wrong here?

**Comment by Vali-98** [comment]
> Am I doing something wrong here?

No this is simply how LLMs function, they take a step to consume context and build the KV. 

Next time, I would recommend not bringing up unrelated topics. This is an issue tracker not code support forum.

**Comment by Dhruvanand24** [comment]
sure
