### ISSUE TITLE
Invalid File Type

### ISSUE THREAD

**Issue by vladbrox** [Vali-98/ChatterUI#21]
When  I want to load .gguf model, I have this error

**Comment by Vali-98** [comment]
Could you provide a link to the model used?

**Comment by vladbrox** [comment]
I used this one - https://huggingface.co/second-state/Phi-3-mini-4k-instruct-GGUF/blob/main/Phi-3-mini-4k-instruct-Q2_K.gguf, and some other, but I had 'Invalid File Type' error

**Comment by Vali-98** [comment]
I cannot replicate this issue. Need some info:

- Can you try redownloading the model?
- What android version are you using?
- What device are you using?
- What ChatterUI version are you running?

**Comment by vladbrox** [comment]
1) No, I download model once
2) I use EMUI on Android 12
3) HUAWEI nova 12s
4) v0.7.5

Ps I'm sorry for my English, I don't know it very well.

**Comment by vladbrox** [comment]
I redownload model and error save

https://github.com/Vali-98/ChatterUI/assets/119420130/70798939-96c9-4442-ae32-484771444f32

**Comment by Vali-98** [comment]
You are trying to load the model in the wrong menu. You have to use API > Local > Import Model
Then load the model and it should work.
