### ISSUE TITLE
Re-Editing message can be impossible

### ISSUE THREAD

**Issue by johnr-de** [Vali-98/ChatterUI#22]
Hi, 
Vali-98, great app, thanks for your efforts!
Sometimes, if you re-edit chat sections, 
- the editor window seems fixed on the bottom of the screen, and when trying to edit, you cant see what you're editing at all,
- as the edit window may be "below" the keyboard or the lower display border...
- Also, if chat messages are longer, the waste basket symbol on the left and the confirm symbol on the right disappear.
See screenshots for details.
Thkx.

If you try to edit the last message in the following chat, the edit windows appears only at the bottom of the screen with only a few lines visible, and the rest and the _waste basket_ and _confirm_ symbols are "below" the lower screen borders:
![Screenshot_20240520_211508_ChatterUI](https://github.com/Vali-98/ChatterUI/assets/45752370/517c8fdf-1740-449d-9c66-25f8ef968f9b)

Once you click into the edit area, the keyboard pops up "over" the edit window. All you see is nothing any more:
![Screenshot_20240520_211537_ChatterUI](https://github.com/Vali-98/ChatterUI/assets/45752370/91a2818f-3c6a-4919-9db7-8f181c507ab6)

**Comment by Vali-98** [comment]
This is interesting, I've never seen this kind of behavior before. Could you provide your device / OS? This may be a platform dependent bug. As far as I can tell this editor functions properly on Samsung / Xiaomi devices.

**Comment by johnr-de** [comment]
Samsung Galaxy S23+ / One UI 6.1 / Android 14

**Comment by Vali-98** [comment]
So my prediction is that there is some issue with how the editor is animated, and I've made a test build for this:
https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.7-beta

Go to Drawer > Gear Icon (on top Right) > Disable `Animate Editor` 

Please report back if this fixes it, thanks!

**Comment by johnr-de** [comment]
I guess this fixes it.

Edit Window:
![Screenshot_20240522_173716_ChatterUI_sm](https://github.com/Vali-98/ChatterUI/assets/45752370/163f4e74-8b69-48f1-ba4c-32007db6b886)

Text editing mode:
![Screenshot_20240522_173727_ChatterUI_sm](https://github.com/Vali-98/ChatterUI/assets/45752370/9468a55c-4ab0-4af3-ad54-743d78ade871)

**Comment by Vali-98** [comment]
This still isnt an ideal solution, so I may notify this issue from time to time if there are any changes that may fix the underlying bug. Happy to hear the current bandaid fix works!
