### ISSUE TITLE
android Feature Request Voice mode.

### ISSUE THREAD

**Issue by nntb** [Vali-98/ChatterUI#23]
I would like to see a voice mode where it listens then responds with a nice animation on the screen similer to chatgpts chat mode. maybe a setting to swap the animation for a animtion of the avatar of the charature. maybe have it pulse when the tts talks. maybe intagrate kaldi tts into it to allow onnx voices.

**Comment by Vali-98** [comment]
This kind of integration is extremely difficult and will likely not be added anytime soon, but I will leave this issue up as a possible feature note. Thanks for using the app and for the suggestion.

**Comment by nntb** [comment]
sure thing just a idea. take it or leave it. its somthing i would personaly like to have.

**Comment by Katehuuh** [comment]
> This kind of integration is extremely difficult and will likely not be added anytime soon, but I will leave this issue up as a possible feature note. Thanks for using the app and for the suggestion.

Voice mode/hands-free is a great feature, possibly use [whisper.rn](https://github.com/mybigday/whisper.rn) listed from [ggerganov/whisper.cpp](https://github.com/ggerganov/whisper.cpp?tab=readme-ov-file#bindings); by recording audio chunks, until no speech is detected.

---

Would be good to save RAM by using Q4/Q8 cache in [llama.rn](https://github.com/Vali-98/cui-llama.rn)?

**Comment by Vali-98** [comment]
> > This kind of integration is extremely difficult and will likely not be added anytime soon, but I will leave this issue up as a possible feature note. Thanks for using the app and for the suggestion.
> 
> Voice mode/hands-free is a great feature, possibly use [whisper.rn](https://github.com/mybigday/whisper.rn) listed from [ggerganov/whisper.cpp](https://github.com/ggerganov/whisper.cpp?tab=readme-ov-file#bindings); by recording audio chunks, until no speech is detected.

This was a consideration yes, the issue with many of these features is more about interfacing it smoothly.

> Would be good to save RAM by using Q4/Q8 cache in [llama.rn](https://github.com/Vali-98/cui-llama.rn)?

Q4/Q8 caching requires Flash Attention, which in turn needs CUDA which isn't available on android.

**Comment by Katehuuh** [comment]
> This was a consideration yes, the issue with many of these features is more about interfacing it smoothly.

Agree, but as a priority, Users here likely run models locally over using a provider, which is already possible on any API _Chat_ playground.

> Q4/Q8 caching requires Flash Attention, which in turn needs CUDA which isn't available on android.

<details> <summary><a href="https://play.google.com/store/apps/details?id=com.layla">layla</a> does have Flash Attention but no CUDA so "zero benefits"?</summary> <br>

[r/LocalLLaMA Report: "Flash Attention feature yielded zero benefits"](https://www.reddit.com/r/LocalLLaMA/comments/1bsnifx/comment/l25mfui/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)


![layla-Flash-Attention_Screenshot](https://github.com/user-attachments/assets/887806f8-19d2-48a7-97bf-aa6629b7bfbc)

---

Except for longer waits with long-context `prompt processing`, [ChatterUI](https://github.com/Vali-98/ChatterUI) on `Snapdragon 8 Gen 3` has been the fastest in `generation` compared to [maid](https://github.com/Mobile-Artificial-Intelligence/maid), [aub.ai](https://github.com/BrutalCoding/aub.ai), [pocketpal-ai](https://github.com/a-ghorbani/pocketpal-ai) backed by  _llama.cpp_, [MnnLlmChat](https://github.com/alibaba/MNN/tree/master/apps/Android/MnnLlmChat), [Cactus Chat](https://github.com/cactus-compute/cactus), [ZentithLLM](https://play.google.com/store/apps/details?id=in.nishantapps.zentithllmai), [Apollo Liquid](https://www.liquid.ai/apollo), [inferra](https://github.com/sbhjt-gr/inferra) and even with GPU (Adreno) support in [ExecuTorch Alpha](https://pytorch.org/executorch/main/llm/llama-demo-android.html), [mlc-llm](https://github.com/mlc-ai/mlc-llm), [google-ai-edge/gallery](https://github.com/google-ai-edge/gallery). [LMstudio IOS](https://apps.apple.com/us/app/locally-ai-by-lm-studio/id6741426692) (MLX)
Often explain with sub-optimal or not available CPU thread options.

</details>

**Comment by Vali-98** [comment]
> Agree, but as a priority, Users here likely run models locally over using a provider, which is already possible on any API Chat playground.

Technically, a voice mode would be compatible with both local and API providers if implemented right. It really is all down to figuring out how to integrate it into the UI.

> [layla](https://play.google.com/store/apps/details?id=com.layla) does have Flash Attention but no CUDA so "zero benefits"?

I did read into the flash attention implementation. Last I checked, there is a 'cpu' implementation for FA, but only for comparison testing with its cuda implementation with no actual perf benefit.

> Except for longer waits with long-context prompt processing, [ChatterUI](https://github.com/Vali-98/ChatterUI) on Snapdragon 8 Gen 3 has been the fastest in generation compared to [maid](https://github.com/Mobile-Artificial-Intelligence/maid), [aub.ai](https://github.com/BrutalCoding/aub.ai) backed by llama.cpp, and even with GPU (Adreno) support in [ExecuTorch Alpha](https://pytorch.org/executorch/main/llm/llama-demo-android.html), [mlc-llm](https://github.com/mlc-ai/mlc-llm).

Is this using Q4_0_4_8 models? That specific quantization format improves prompt processing somewhat. Technically all llama.cpp backed apps *should* perform identically, so there probably just is some misconfiguration somewhere on their part.

**Comment by Katehuuh** [comment]
> > Except for longer waits with long-context prompt processing

> Is this using Q4_0_4_8 models

No intensive testing but I've used _normal_ 7B-`Q4_K_M.gguf`, First load and processing of 1k+ token, long-context character-card and compare to [maid](https://github.com/Mobile-Artificial-Intelligence/maid).

**Comment by Vali-98** [comment]
> No intensive testing but I've used normal 7B-Q4_K_M.gguf

I'd suggest you also test Q4_0_4_8 due to its speed benefits on Snapdragon 8 devices. It's almost a 50% improvement to prompt processing.

**Comment by Vali-98** [comment]
I think  I will be closing this issue, as a voice mode chat is currently not in scope of any future updates.

**Comment by Katehuuh** [comment]
> I will be closing this issue, as a voice mode chat is currently not in scope of any future updates.

Sorry for bring this up again, I found it interesting chatting "hands-off" and wonder what makes it difficult to implement voice mode? Since ChatterUI already uses built-in TTS component; it could also use native microphone (SpeechToText #226) for continuously loop TTS->LLM->STT.
- `@react-native-voice/voice` supports iOS and would be smth like this [patch.diff](https://github.com/user-attachments/files/23064568/patch.diff.txt):
  - Listen → detect end of speech → send to LLM → TTS speaks → auto-listen again.

Nowadays, we have faster than whisper like `parakeet-tdt-0.6b-v3-onnx` and `mistralai/Voxtral-Small`, but I understand those are not built-in.

I also wanted your opinion on the alternative backend [cactus-compute/cactus](https://github.com/cactus-compute/cactus)?

**Comment by Vali-98** [comment]
> Sorry for bring this up again, I found it interesting chatting "hands-off" and wonder what makes it difficult to implement voice mode? 

There isn't really any technological roadblocks for this, STT libraries are plentiful. It's just a matter of prioritizing features with the limited free time I have.

> I also wanted your opinion on the alternative backend [cactus-compute/cactus](https://github.com/cactus-compute/cactus)?

The speed benefits seem minimal, and there are far fewer people quanting for cactus vs GGUF.
