### ISSUE TITLE
App crashes after install to the newest version 0.5.5

### ISSUE THREAD

**Issue by doncamillo0815** [Vali-98/ChatterUI#3]
After upgrading to v0.5.5, the app crashes whenever I attempt to open a new chat.
Additionally, upon fresh installation of v0.5.5, the app crashes when I try to open Settings/Presets or Settings/Instruct.
I am using the API: Text Generation Web UI.

Request:
Is it possible to publish the previous versions (v.0.5.0-0.5.4) also under releases.
I can't use your app right know because it is broken and don't have the last download anymore.

Thanks for your good work.

**Comment by Vali-98** [comment]
Hey there, I have reuploaded v0.5-v0.5.4 while I investigate the issue. Thanks for using the app.

**Comment by Vali-98** [comment]
This has been fixed in: 2151df8f521bc48c70695f32bb29a84eda22b285

Issues fixed:
- New chat creation causing a crash
- App initialization not creating default preset and instructs

v0.5.6 will be uploaded shortly.
