### ISSUE TITLE
Eternally sorry 

### ISSUE THREAD

**Issue by Fau57** [Vali-98/ChatterUI#31]
if this is obvious to others but I don't really get how to feed or link my local models. There's no obvious way to link gguf models, is that wrong, do I need gbml?

**Comment by Vali-98** [comment]
To use GGUF models, go to API > Local > Import Model

Once you've imported the model, press 'Load Model' and wait for it to load, then you can start using it.

**Comment by Fau57** [comment]
Thanks so much I just must not have scrolled the right way or something. Appreciate your taking the time on saucy a little issue
