### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by DeveloperBloke** [Vali-98/ChatterUI#32]
I've tried 3 different local models and they all crash before a response is even generated , in using an s20 with 8gb ram and i ran the same models on various app smoothly
![Screenshot_20240609_055058_Device care](https://github.com/Vali-98/ChatterUI/assets/158039134/78697944-94b8-49cf-9f5d-9084cbd8e6b6)

**Comment by Vali-98** [comment]
This has been reported, not sure why its happening, but will be investigating and taking down 0.7.7 until this is resolved.

**Comment by Vali-98** [comment]
This has been fixed in 450f716faf8817c14dfef90bd2c70cde47522fcc

Added a patched version v0.7.7a to the release: https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.7
