### ISSUE TITLE
TTS not working properly

### ISSUE THREAD

**Issue by DeveloperBloke** [Vali-98/ChatterUI#34]
I've tested the TTS feature on multiple devices and its not working properly and speech output isn't generated

https://github.com/Vali-98/ChatterUI/assets/158039134/244d5347-d0ee-41de-bfd6-9712c3715a91

https://github.com/Vali-98/ChatterUI/assets/158039134/c86cbca4-1fc5-4e59-943a-6c658b0d2811

**Comment by Vali-98** [comment]
This was just fixed in 1c35adae91ec8877ba42f84d7dedfc68f21bd02e

v0.7.7b with the fixes is now available: https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.7
