### ISSUE TITLE
Not sure what's going on

### ISSUE THREAD

**Issue by Fau57** [Vali-98/ChatterUI#35]
Try as I might I can't seem to get it to actually reply to me maybe I'm using the wrong model quantization I don't think so I will send my logs but I'd rather not post them publicly so let me know

**Comment by Vali-98** [comment]
Please provide some more information:

1. Are you sure you are loading the model?
2. If you are crashing, be sure to download v0.7.7b that was added to the release page: https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.7
3. Be sure to use the correct prompt format for your model.
4. If possible link the model used.

A simple "It doesn't work" isn't very helpful.

**Comment by Fau57** [comment]
Yea fair enough sorry, I believe phi so serious at 3b q4 k m or s. The prompt was right. And yes it would load with 1 core and then spinning wheel for over 20 minutes. Its a Samsung s20 FE. Not the best or worst hardware. 
I'll double check version here in a second.

**Comment by Vali-98** [comment]
>  running 0.7.7 already, and at 2 threads it quit after about 30 seconds.
Be sure to use 0.7.7b. 
The original 0.7.7 has a bug that causes it to crash on inference.

Also, it may be worth using v0.7.8beta1 to test a fixed version of the autoloading:
https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.8beta
