### ISSUE TITLE
Option to disable splash screen at intro

### ISSUE THREAD

**Issue by Sphyker789** [Vali-98/ChatterUI#36]
Can you include an option to disable the splash screen when the app is opened as it takes 2 seconds and it's kind of annoying

**Comment by Vali-98** [comment]
Hey there, the splash screen actually only runs while the app is loading and while the database isn't ready. This isn't an arbitrary splash screen, its react-native initiating.

**Comment by Sphyker789** [comment]
Could you please make it go away faster as it takes around 2 seconds + and
it gets kind of annoying every time the app is closed and opened

**Comment by Vali-98** [comment]
I do not think that is possible as its an issue with react-native itself.
