### ISSUE TITLE
bug: response slows down with each reply on local llm until a new empty chatlog is created

### ISSUE THREAD

**Issue by Sphyker789** [Vali-98/ChatterUI#37]
The responses get slower with each reply but are fast when a new character and clean chat log is created, I've tested this on 3 separate devices and gets slow specially when using the "load chat on startup" feature?

**Comment by Sphyker789** [comment]
I am currently using v0.7.8beta and the responses become progressively slower with each reply

**Comment by Vali-98** [comment]
> I am currently using v0.7.8beta and the responses become progressively slower with each reply

Yes, that is normal behavior. Thats how LLM's tend to function as max grows. That said, if your Max Context is set too low it may be truncating too much. Most models are at least 2048-4096 nowadays.
