### ISSUE TITLE
Clear chat button feature

### ISSUE THREAD

**Issue by Sphyker789** [Vali-98/ChatterUI#38]
Could you add a clear chat button in the chat interface that allows user to click it and start a a new chat easily.

**Comment by Vali-98** [comment]
Is there an issue with going to Menu > Chat History > New Chat (the plus sign)?

**Comment by Sphyker789** [comment]
It's slower and it keeps the old chat logs which fills up the cache and slows down the application performance

**Comment by GameOverFlowChart** [comment]
> Is there an issue with going to Menu > Chat History > New Chat (the plus sign)?

Other than it takes a lot of clicks there is another issue with that delete button. Clicking slightly above or below the trash can but still inside the box will reopen the chat instead of deleting. So it's very painful. The whole square around the trash can should be the button not just the icon itself.

**Comment by Vali-98** [comment]
> It's slower and it keeps the old chat logs which fills up the cache and slows down the application performance

This shouldn't be the case, chat logs are stored in a SQLite locally which is rather fast, only only the current log is loaded at a time and is updated optimisitically, so you never really have to wait for the read/writes aside the first load, which itself is pretty quick.

> Clicking slightly above or below the trash can but still inside the box will reopen the chat instead of deleting.

This is a known problem on several menus (character list, chat list, user list). I am planning for further styling revisions to amend this and several other menus.

As far as the original issue is concerned it could be done easily as a menu option, though I will investigate alternatives.

**Comment by Vali-98** [comment]
This likely won't be added. Improvements to the chat creation and management will be made instead.
