### ISSUE TITLE
please add a simple text2image from stable-diffusion.cpp

### ISSUE THREAD

**Issue by Amin456789** [Vali-98/ChatterUI#40]
hi
thank u for this great app
please consider add a simple text 2 image form stable-diffusion.cpp that supporst gguf files for image generation, or please make the koboldcpp to generate image too

thank u

**Comment by Vali-98** [comment]
1. Stable-diffusion-cpp would require writing react-native bindings which is not a small task. It's not impossible, and it may be better to use fastsdcpu instead, but its unlikely to be added.

2. koboldcpp - It's not impossible to add this, however integrating this for multimodal use is not easily done, though I would like to see this added too.

**Comment by Vali-98** [comment]
After some review, the integration of SD-cpp is inefficient, and may be better to integrate projects like `fastsdcpu`.

That said, image support for the app is planned, just not at this time or anytime soon.
