### ISSUE TITLE
Urgent feature request 

### ISSUE THREAD

**Issue by DeveloperSponsor** [Vali-98/ChatterUI#43]
If you add a simple chat to text file feature I promise I will donate to your patreon account as soon as the feature is added

**Comment by Sphyker789** [comment]
Yes me too please add this feature asap

**Comment by TrendingApp** [comment]
please make the chosen text file auto-load on app-start similar to "the model auto loading" feature

**Comment by Vali-98** [comment]
It is very obvious that you are using duplicate accounts to ask for features. Please do not sockpuppet accounts as its against Github's ToS. 

As I've said before, this feature will not be added soon, please stop spamming feature requests and offering monetary incentive. It is very unbecoming.
