### ISSUE TITLE
Play Protect marking this app as potentially harmful

### ISSUE THREAD

**Issue by netroy** [Vali-98/ChatterUI#46]
I installed the latest release from github, and got this warning.
![Screenshot_20240710-210930](https://github.com/Vali-98/ChatterUI/assets/196144/018c8cb6-74d5-496c-bd81-c6855abcfc11)

I'm not sure why this happens, but just wanted to let you know.

**Comment by Vali-98** [comment]
This is known as the APK isn't signed for the playstore. The only fix would be to properly submit a playstore version of the app, but its somewhat unneeded as this app isn't a very useful to a layman user.
