### ISSUE TITLE
When can we expect being able to chat with a webpage or  a document

### ISSUE THREAD

**Issue by softpedia-inc** [Vali-98/ChatterUI#47]
More apps have been competing on having the option to chat with a webpage or a document as a way to get precise information from that specific document or webpage. Can we expect having such  revolutionary features any time in the future?

**Comment by Vali-98** [comment]
Duplicate of #41 - It is possible and I have been testing possible storage solutions, but there are no concrete plans at the moment to add this soon, many other parts of the app need attention.
