### ISSUE TITLE
Removing a Failed Imported Character is not possible

### ISSUE THREAD

**Issue by 4riw** [Vali-98/ChatterUI#48]
Hi,
I tried to import a v2 card in .png format into the app. Because of the lack of visual cues and a long processing time, the import process failed somehow. The character's list is now cluttered with the failed entry that cannot be removed.
Wouldn't it be cool to have a swipe-to-delete option?

Produced on Android 11, Samsung A315G using v 0.7.8.
The char card imported as png file from chub ai.

![Screenshot_20240719-220610_ChatterUI_1](https://github.com/user-attachments/assets/65b48ef7-a08a-41c0-a71d-d12cfc9e89ef)

**Comment by 4riw** [comment]
This is the problematic character card.
chub.ai/characters/frenchroccocco/possessed-alice-63a5f619

**Comment by Vali-98** [comment]
A bit late on this, but with the ongoing UI reworks, characters can now be deleted on failure, and I have since improved the import routine to reject malformed cards for effectively:
![image](https://github.com/user-attachments/assets/858078db-2088-4090-a52a-fc04aeb5c28c)
