### ISSUE TITLE
[Enhancement - Bug] Dyn Temp, temperature_last for ooba

### ISSUE THREAD

**Issue by Knifemint** [Vali-98/ChatterUI#5]
Hi again, thanks for implementing some of my requests. I just tested v0.6.5 and there are few things I recommend for improvement:

- [Presets - Bug] Keeps reverting back to Default profile instead of a custom profile when returning back to Settings.
- [Presets - Enhancement] Dynamic Temperature implementation.
- [Instruct - Bug] Input Sequence [INST] is missing on card's Description but Output Sequence [/INST] exists.
- [Instruct - Bug] Include Names is not working.
- [Text Gen WebUI - Bug] `temperature_last` is required for coherency when `min_p` is used. Text Gen Web UI with 2.0 `temperature`, 1.0 `top_p`, 0.05 `min_p` is incoherent in ChatterUI but not on SillyTavern.
- [Text Completion - Bug] `min_p` is not working for both kcpp & ooba.

Hope it helps!

**Comment by Vali-98** [comment]
Hey there, I will get to this in time and most of these issues seem like pretty easy fixes. I do need further elaboration on this point:

> [Instruct - Bug] Input Sequence [INST] is missing on card's Description but Output Sequence [/INST] exists.

Can you explain what exactly you mean by this?

Also a side note:

> [Instruct - Bug] Include Names is not working.

Not much of a bug, more of a 'thing that has button but doesnt actually work' that I have yet to get to.

**Comment by Knifemint** [comment]
> [Instruct - Bug] Input Sequence [INST] is missing on card's Description but Output Sequence [/INST] exists.

Attached below are verbose log from koboldcpp and text-generation-webui:
[Koboldcpp.txt](https://github.com/Vali-98/ChatterUI/files/14066754/Koboldcpp.txt)
[TextGenWebUI.txt](https://github.com/Vali-98/ChatterUI/files/14066757/TextGenWebUI.txt)

For this one, the prompt before the "Write Assistant's next..." has no Input Sequence which is supposed to have `[INST]` (I'm using a Mistral instruct straight exported from ST and imported to ChatterUI). The card's description did end with Output Sequence which is `[/INST]`.

There were also additional spaces in the ChatterUI logs which sometimes results to adding additional space before the actual response. I'm not sure if this would affect the inference quality but just letting you know if it would.

**Comment by Vali-98** [comment]
These issues have been resolved in: https://github.com/Vali-98/ChatterUI/releases/tag/v0.6.6

Except for one:

> [Instruct - Bug] Input Sequence [INST] is missing on card's Description but Output Sequence [/INST] exists.

It seems that SillyTavern automatically defaults to using the `Input Sequence` when a `System Sequence Prefix` is missing. However, as some may want to have no `System Sequence Prefix`, ChatterUI does not default to using the `Input Sequence`. 

To fix this, I suggest adding `[INST]` to `System Sequence Prefix`.
