### ISSUE TITLE
Multiple model configs, with fallback to local model when offline

### ISSUE THREAD

**Issue by lee-b** [Vali-98/ChatterUI#50]
It would be really great if you could configure a large remote model and a small local model, and have it fall back to the local model when offline.

**Comment by Vali-98** [comment]
This isn't always possible as many backends don't have a heartbeat function. The primary concern is that you may be using an endpoint and it fails to some network hickup and fallsback to local. It would be annoying to keep swapping back to network connections manually, and doing it automatically also has a host of potential issues.

Though I do think this is possible, its certainly not on the priority.

**Comment by Vali-98** [comment]
Closed due to low demand for feature.
