### ISSUE TITLE
Generic Chat Completion 

### ISSUE THREAD

**Issue by suushore** [Vali-98/ChatterUI#51]
Sir, would you plan to add Generic **Chat Completion** (not Generic Text Completions)?

Some apis, like **Groq**, only have a url. like 

> "...../v1/chat/completions"

And is it possible to add google **Gemini** api to the app?

**Comment by Vali-98** [comment]
> Sir, would you plan to add Generic Chat Completion (not Generic Text Completions)?

This is planned, I just dont have the time for it.

> And is it possible to add google Gemini api to the app?

This will need to be looked into.

**Comment by Vali-98** [comment]
Added in: [a8c0708](https://github.com/Vali-98/ChatterUI/commit/a8c070888d2969eafdf65d44356be383e8674126)

**Comment by tazztone** [comment]
amazingly i could get groq to work :)
![Screenshot_20241206_234336_ChatterUI](https://github.com/user-attachments/assets/01efaff3-6659-4951-9134-793e8fc90ab2)
