### ISSUE TITLE
Multiple Stop sequences

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#53]
Some models have officially multiple stop sequences. Or sometimes you need multiple stop sequences for different reasons. I think the easiest way would be a + button which adds a new text box for stop sequence 2 and so on. I wouldn't separate multiple stop sequences with a "," or something, that would be too complex as you would also need to be able to escape that and so on.

**Comment by Vali-98** [comment]
Actually the current implementation does use a `,` seperator for multiple stop sequences which admittedly is pretty poor implementation. I will look into proper multistop sequences.

**Comment by mlsterpr0** [comment]
Sry for off topic, just can't find a way to give feedback or suggestions. I love this app, it has all i need and just works. Just one option i miss, is ability to change font size. It's way too small on my smartphone. Thanks!
