### ISSUE TITLE
Bug with new version

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#55]
So I did update to 0.7.9 (the change log reads amazing much more development under the hood than I realized).
But there is a Bug I don't know what causes it but the symtome is that the model now begins it's outputs always with the system prefix (<|im_start|>system in my specific case). I'm not sure if it's added by the app or if some other problem leads to the model generating it somehow. And of course the rest of the output is also useless if it thinks that it writes a system prompt.

**Comment by Vali-98** [comment]
Has your Instruct settings changed? Try mess around with it based on which model you are using. Be sure to match the prompt format for the model used.

**Comment by GameOverFlowChart** [comment]
This one has no system prompt, it was working before but now even that doesn't work.

![Screenshot_2024-08-02-16-45-29-18_46c75b0d777501bc756459feb21fe8e7](https://github.com/user-attachments/assets/90629f78-e69b-48e1-947d-a27bcbd8c493)

**Comment by Vali-98** [comment]
Could you try enable `Print Context` in settings? Something seems wrong about how the context is formatted.

**Comment by GameOverFlowChart** [comment]
![chat](https://github.com/user-attachments/assets/f74ecdf3-0fb1-46df-9736-18da3c405d5a)

I think both the output prefix, and even the message of the user is completely missing. I did some more tests after this screenshot, and it seems like the input (except the system message) plays no role at all.

**Comment by Vali-98** [comment]
A very interesting bug, 

A few more questions:
- Assuming from the screenshots, this is using the local API, correct?
- It seems that you have disabled the first message? 
- What character card did you use? The name being Null is somewhat worrying.

**Comment by GameOverFlowChart** [comment]
> A very interesting bug,
> 
> A few more questions:
> 
> * Assuming from the screenshots, this is using the local API, correct?
> * It seems that you have disabled the first message?
> * What character card did you use? The name being Null is somewhat worrying. Have you tried this on a different character card? Try making one with all its fields filled.

1 Yes it's a local model

2 Yes the model isn't trained for that case, it still did work with a first message but once you implemented the feature to disable it I did and the first message field is empty 

3 nah I just used Null as a creative name for a character card with an empty system message because I'm a Java guy :D it's not new and never made problems with older versions of the app. I also tried with other character cards which have other names, and as I said my conversation is that the system message is the only thing that is correctly feeded to the model, so I assume the problem does not lie at the character cards as they still work correctly. It's the user message that's missing for sure.

**Comment by Vali-98** [comment]
Well, give the latest a go and see if this is fixed. I find it odd that absolutely nothing gets added:
https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.9a

**Comment by GameOverFlowChart** [comment]
> Well, give the latest a go and see if this is fixed. I find it odd that absolutely nothing gets added: https://github.com/Vali-98/ChatterUI/releases/tag/v0.7.9a Supposedly, at least something should get added, even at 0 context.

Still the same issue:
![bob](https://github.com/user-attachments/assets/8ec79459-76e4-4bad-93a8-79e5d306eb15)

**Comment by Vali-98** [comment]
Im a bit stumped on this, I am unable to reproduce it at all. 

One last check:
- Could it be an issue with your User card?
- This may be an issue with your Generated Tokens limit in samplers. If its set too high, say, 2000 generated amount for 2048 context, only 48 tokens are allowed for the prompt builder. This was not the case with previous builds which caused context to break afterwards.

**Comment by GameOverFlowChart** [comment]
I'm not really familiar with the user card since I don't need it and don't know how exactly it's injected into the conversation. I left it blank but I had a similar idea so I just saved the empty user card again but it didn't change anything. I will have a look into my token limit. 

Another idea I have is deleting all user data in the app and trying again (or a fresh install). But I would have to back up settings like character cards and sampler and stuff so it would take time until I can try that. But if that works that would just be a workaround and any other update could lead to something similar.

**Comment by GameOverFlowChart** [comment]
Vali you are

> Im a bit stumped on this, I am unable to reproduce it at all.
> 
> Two last checks:
> 
> * Could it be an issue with your User card?
> * This may be an issue with your Generated Tokens limit in samplers. If its set too high, say, 2000 generated amount for 2048 context, only 48 tokens are allowed for the prompt builder. This was not the case with previous builds which caused context to break afterwards.

Nice, It was the generation token limit which I had at 8192, which isn't what I wanted anyway, lowered it and it works fine.

**Comment by Vali-98** [comment]
Great to see this resolved. That said, this does show a failure of the Sampler settings not reflecting potential downsides of setting said value too high, so its worth considering some warning about this.
