### ISSUE TITLE
Nice.. but stop sequences are needed.

### ISSUE THREAD

**Issue by Zibri** [Vali-98/ChatterUI#56]
On the android app.. grmma-2 2b
![Screenshot_2024-08-03-02-18-00-522-edit_com Vali98 ChatterUI](https://github.com/user-attachments/assets/8ec04fb9-950c-4bfd-8f9f-aec99d48067a)

**Comment by 0wwafa** [comment]
I solved by adding <end_of_turn> in the instruct page. but it would be better to have multiple stop words, not just one.

**Comment by Vali-98** [comment]
You can currently add multiple stop sequences by seperating them with `,`, eg `<eos>,<end_of_turn>`.

Its not the best solution as it hinges on `,` never being used in the stop sequence, but it'll work.

**Comment by 0wwafa** [comment]
Yes.. I found out yesterday, I triend with comma and it worked.
