### ISSUE TITLE
Support for quant Q4_0_4_4?

### ISSUE THREAD

**Issue by Slavczays** [Vali-98/ChatterUI#57]
Please add support for Q4_0_4_4 quant on older soc (like sd845) if possible. You mentioned [here](https://www.reddit.com/r/LocalLLaMA/comments/1ebnkds/llamacpp_android_users_now_benefit_from_faster/) about optimized quantization Q4_0_4_4 - **fallback for most arm soc's without i8mm** (I suppose sd845 meets the requirements).It would be cool feature for owners of phones with older soc.

**Comment by Vali-98** [comment]
It seems that Q4_0_4_4 is failing to load due to not disabling GGML_USE_LLAMAFILE=OFF in the Cmakefile for `cui-llama.rn`.

I will need to investigate if disabling this breaks anything first.

**Comment by Slavczays** [comment]
thanks for the quick reply, sure, I'll wait patiently, maybe it'll be fixed. thanks

**Comment by Vali-98** [comment]
Actually I just tested the Q4_0_4_4 quant on an older device (arm64-v8a, doesn't seem to have i8mm) and it works on the latest build.

I'm not sure if this is true for all arm devices due to the variety of configurations they are made in.

**Comment by Slavczays** [comment]
I tried latest build with gemma-2-2b-it-Q4_0_4_4.gguf. Sadly app crash when loading model:( Works ok with standard quants gemma q5_k_m. My phone: Pocophone F1, SD845, 6gb ram, Android 14

**Comment by Vali-98** [comment]
Checking your device it should work optimally with Q4_0_4_4, unless it sneakily has i8mm for whatever reason. I cannot ascertain as to why it crashes as it occurs far too internally in the c++ code to see. Just to confirm, it also doesn't work with Q4_0_4_8 yes?

**Comment by Slavczays** [comment]
Sadly, gemma 2 2b Q4_0_4_8  doesn't work too:(

**Comment by Vali-98** [comment]
Yeah, then I really have zero clue as to why this happens. It's possible that your SOC doesn't support ARM Neon at all, but checking its spec sheet it should be arm64-v8.2 which should at least have neon with dotprod/fp16.

**Comment by Vali-98** [comment]
I think I'll close this issue for now, as there is no real way for me to test this.
