### ISSUE TITLE
Add DRY sampler

### ISSUE THREAD

**Issue by OXKSA1** [Vali-98/ChatterUI#59]
Hello, i hope you add DRY sampler its can force the models to try to be less repetitive while still coherent

**Comment by Vali-98** [comment]
Hey there! This is on the todo list, but there are reworks to the existing sampler management under the hood to complete before I can commit to adding more fields.

**Comment by Vali-98** [comment]
Completed in: [a5eb86c](https://github.com/Vali-98/ChatterUI/commit/a5eb86cd0b3a89535fc931bbf252df00bdcf81b1)
