### ISSUE TITLE
GPT models are not working.

### ISSUE THREAD

**Issue by Zaurio20** [Vali-98/ChatterUI#61]
I'm using OpenRouter, and the GPT-4o models aren't generating anything. The messages remain blank.

**Comment by Vali-98** [comment]
I've had this reported several times, will look into it.

**Comment by Vali-98** [comment]
> GPT-4o models

Could you check what is output in your logs? I have not been able to reproduce this.

**Comment by Vali-98** [comment]
I think I've figured out the issue, for some reason I included `response_format: { type: 'json_object }` in the OpenRouter call. Removing this seems to have fixed it for GPT-4o:  [a4023a0](https://github.com/Vali-98/ChatterUI/commit/a4023a03070fa83f8e6fedb40240ec22a18c0045)

I will upload v0.7.9d with this fix later.
