### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Nullimw** [Vali-98/ChatterUI#7]
I am using the latest version, i have 4 gb Ram and i am using tinyllama chat gguf

**Comment by Vali-98** [comment]
Hey there could you provide more information about your device?

In the Logs menu, does it indicate why the loading fails?

Its possible that your device is incompatible with llama.rn or simply doesn't have enough memory to use run it.

**Comment by Nullimw** [comment]
Redmi note 4 snapdragon

**Comment by Nullimw** [comment]
I think it was because of the ai just erroring
