### ISSUE TITLE
Increase max context again

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#70]
I don't know if it would run on any phone today with that context size but llama 3.1 has a context size of 131072. I'm running it at 32768 for now and it does work.

**Comment by Vali-98** [comment]
Though this is possible, its very unrealistic to actually run this.

On llama31-8b, 32k context is already pushing at about 6gb of memory for context alone alongside the 4GB for the model, around 10-11GB total which is realistic for modern 16GB phones.

With 132k context, this balloons to about 28-29GB of memory total. I don't think there are many mobile devices with that much memory just yet.
