### ISSUE TITLE
Support Azure OpenAI

### ISSUE THREAD

**Issue by mydreamworldpolly** [Vali-98/ChatterUI#71]
Could you please support Azure openai?  I would like provide my C# code to show the differences.  

if (aiModel.isAzure)
{
    httpClient.DefaultRequestHeaders.Add("api-key", aiModel.key);
}
else
{
    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", aiModel.key);
    requestBody["model"] = aiModel.model_name;
} 
Besides, users should input Azure endpoints, like https://xxx.openai.azure.com/openai/deployments/{deployment name}/chat/completions?api-version=2024-02-01

**Comment by Vali-98** [comment]
This can be done, I'll just need to find time to do it.

**Comment by Vali-98** [comment]
This may be solved with the new API Configuration system: https://github.com/Vali-98/ChatterUI/discussions/126
