### ISSUE TITLE
generic chat completions

### ISSUE THREAD

**Issue by 4riw** [Vali-98/ChatterUI#72]
Suggestion:
Could you make the endpoint for generic chat completions static, only including "chat/completions"? And the models call too.

Some generous providers who offer free services often create their API URLs in the format, for example, "api.example.com/v2/chat/completions" or "api.example.net/free/chat/completions".

Thank you.

**Comment by Vali-98** [comment]
I will probably change it to require the full URL + API path for the custom configurations, as people tend to have custom API names anyways.

**Comment by ansuckynoob** [comment]
+1, this is actually super common for paid providers too. For example, DeepInfra (https://deepinfra.com/docs/openai_api) is one I'm trying to use with this app but currently can't.

**Comment by Physfock** [comment]
I try to use my provider https://glhf.chat/users/settings/api but it does not work...

**Comment by Vali-98** [comment]
This will probably be fixed with an upcoming rework to the API manager system, as there are many different APIs with unique implementations.

**Comment by Vali-98** [comment]
This may be solved with the new API Configuration system: https://github.com/Vali-98/ChatterUI/discussions/126
