### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#73]
I found a strange behavior. It happens with a specific model or at least the way I trigger it works just with that one (I compared another one and it didn't happen). So the behavior is that during the generation some token or words seem to be repeated often. But once the generation is finished the text turns normal (which is why I think it has to do with the client, not the model). I'm running local on Android as always.
![ZomboDroid_28082024084003](https://github.com/user-attachments/assets/30e01dcd-308e-4b13-82cb-da07744f3780)

This reminds me about emojis they are also shown correctly once the generation is over.

**Comment by GameOverFlowChart** [comment]
Also don't mind the random |} I was playing around with instruct formats as I found this behavior, but the behavior happens independent of the used format.

**Comment by Vali-98** [comment]
Could you provide the model this occurs with? Its very strange indeed. The buffer used to show the output should only ever be concatenated to once per token.

**Comment by GameOverFlowChart** [comment]
> Could you provide the model this occurs with?

Llama-3.1-Storm-8B-Q4_K_S.gguf which Is from here: https://huggingface.co/bartowski/Llama-3.1-Storm-8B-GGUF

This behavior seems only to happen with short input (like in the screenshot). The system message was also empty.

**Comment by Vali-98** [comment]
After some testing, I have been unable to replicate this issue. I think I will close this as the problem itself is both very niche and minor. Feel free to reopen if this issue worsens.
