### ISSUE TITLE
Mistral instruct template

### ISSUE THREAD

**Issue by hugalafutro** [Vali-98/ChatterUI#74]
Hi,
could you add mistral instruct template? I'm too stupid to figure it out trying to copy it from sillytavern settings.

Thanks!

**Comment by kukalikuk** [comment]
+1 for this, my mistral model spitting nonsense with non-mistral instruct

**Comment by Vali-98** [comment]
Addeed in a9f02dde138c790bac63a1840bca405d8f0df90e
