### ISSUE TITLE
Add SAM as a tts option fr

### ISSUE THREAD

**Issue by VHDsdk** [Vali-98/ChatterUI#75]
So theres this lil silly tts voice called sam, i think it would be very cool to have it (not really a feature im desperate for ChatterUI to have. Also, im not sure im allowed to post links here so i wont just to be sure, just search SAM tts on google to find it.)

And yes, V1 Ultrakill haha funny.

**Comment by Vali-98** [comment]
ChatterUI just uses the default android TTS engine for voices. Preferably a native app would add a custom TTS engine to it, but none seem to exist. This is not impossible to do, but it is a bit out of scope.
