### ISSUE TITLE
Support Llama-2

### ISSUE THREAD

**Issue by Katehuuh** [Vali-98/ChatterUI#76]
When loading using 12GB RAM Llama-2-13B [Q4_K_M](https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF), Q2_K or Q4_0_4_8 app does terminate. Had no problem with [maid](https://github.com/Mobile-Artificial-Intelligence/maid). 

---
and I suggest you create `Discussions` tab for simple Q&A.

**Comment by Vali-98** [comment]
The discussion page is now open!

I will get back once I have the model loaded properly, it technically should work, but its possible some flag disables older quantizations.

**Comment by Vali-98** [comment]
ive tested this on my own 12GB phone with no issue, I'm guessing theres some other factor to this that may be specific to your device. For now I think I'll close the issue as there is no easy way for me to test further. Let me know what device you are using and I'll look into if this issue can be reopened.

**Comment by Katehuuh** [comment]
Llama-2 is supported. My mistake `"n_ctx": `**32768**... I thought the context window size would be handled by RoPE or limited by config.

<details><summary>Used external tool;/ ChatterUI logs don't indicate 'Out of Memory.' I recommend adding [RAM usage/Total] in UI.</summary><br>

[adb](https://developer.android.com/tools/releases/platform-tools) `logcat > logs.txt`:
```
ReactNativeJS: {"model":"file:///data/user/0/com.Vali98.ChatterUI/files/models/llama-2-13b-chat.Q4_K_M.gguf","n_ctx":32768,"n_threads":4,"n_batch":16,"n_gpu_layers":0,"use_mlock":true}
...
1169 D lowmemorykiller: critical pressure event triggered
1169 D lowmemorykiller: Ignoring critical pressure event; too many file cache(1856615) are left
1169 D lowmemorykiller: medium pressure event triggered
...
1963  7239 I ActivityManager: Process com.Vali98.ChatterUI (pid 12165) has died: fg  TOP 
1963  2147 I libprocessgroup: Successfully killed process cgroup uid 10456 pid 12165 in 0ms
```

Additionally, I had a larger font size which cut off n_ctx field.
</details>
