### ISSUE TITLE
GPU and NPU acceleration

### ISSUE THREAD

**Issue by Re4mer** [Vali-98/ChatterUI#78]
Hello
Can you please add GPU acceleration support to this app?
Llama.cpp project supports Vulkan API for this purpose. And maybe you can add NPU support as well. It can hugely impact token generation speed.

**Comment by Vali-98** [comment]
I do not believe the Vulkan API is optimized for android, as I have tested before and discussed with the llama.cpp vulkan dev.

For adreno specifically, its a performance deficit to run Vulkan last ive tested.
