### ISSUE TITLE
Text Geneneration Web UI Stream output is wrong

### ISSUE THREAD

**Issue by doncamillo0815** [Vali-98/ChatterUI#8]
v0.7.0
The output repeats the whole tokens instead only adds the new token to the response.

The output looks like this:

user: output the mass of the moon

ai: The The The mass The mass of The mass of the The mass of the moon The mass of the moon is The mass of the moon is approximately The mass of the moon is approximately The mass of the moon is approximately 7 The mass of the moon is approximately 7. The mass of the moon is approximately 7.3 The mass of the moon is approximately 7.34 The mass of the moon is approximately 7.342 The mass of the moon is approximately 7.342 x The mass of the moon is approximately 7.342 x The mass of the moon is approximately 7.342 x 1 The mass of the moon is approximately 7.342 x 10 The mass of the moon is approximately 7.342 x 10^ The mass of the moon is approximately 7.342 x 10^2 The mass of the moon is approximately 7.342 x 10^22 The mass of the moon is approximately 7.342 x 10^22 kil The mass of the moon is approximately 7.342 x 10^22 kilog The mass of the moon is approximately 7.342 x 10^22 kilograms The mass of the moon is approximately 7.342 x 10^22 kilograms. The mass of the moon is approximately 7.342 x 10^22 kilograms. The mass of the moon is approximately 7.342 x 10^22 kilograms. The mass of the moon is approximately 7.342 x 10^22 kilograms.

**Comment by Vali-98** [comment]
Hey there, I actually found this issue on the KAI backend a while ago, the primary issue is that the delimiters used by certain backends is `\r\n` instead of just `\n`, which is out of spec for Text Completions.

This should be fixed on text-generation-webui's side instead. I will put up an issue about this matter.

**Comment by doncamillo0815** [comment]
Thanks, keep up the good work.
