### ISSUE TITLE
Self-signed SSL certificate for API?

### ISSUE THREAD

**Issue by BahamutRU** [Vali-98/ChatterUI#82]
Install root certificate in Android Trusted, but https://… in API doesn't work. =(

**Comment by Vali-98** [comment]
Im not certain what this means, https should work. What error is getting logged?

**Comment by BahamutRU** [comment]
![photo_2024-09-16_09-55-28](https://github.com/user-attachments/assets/2192895c-003b-4ba7-af3e-b8732e7bb068)
![photo_2024-09-16_09-55-29](https://github.com/user-attachments/assets/2ccaba48-e91c-42b3-9d19-7fe767af022d)
I don't know. =(
I added certificate into Trusted (Settings->Security), and it's work in browser, but not in app. =(
![photo_2024-09-16_09-59-16](https://github.com/user-attachments/assets/81b6ece2-b274-40db-8065-727638ffa31f)

**Comment by Vali-98** [comment]
For local IP addresses, I dont think https is required. Have you tried just using http?

**Comment by BahamutRU** [comment]
But I'm not always at home... But the server is.

Screenshot just example, I was at home at the time.

For public IP address, I prefer https. =)

It would be nice if the program took certificates from Encryption & Credentials self-signed CA storage.

I'm not an android developer, but maybe this will help?

https://developer.android.com/privacy-and-security/security-config?hl=ru#TrustingAdditionalCas

```
<certificates src=["system" | "user" | "raw resource"]
              overridePins=["true" | "false"] />
```

> "user" for user-added CA certificates

**Comment by Vali-98** [comment]
At the moment, I'm not too sure what are the possible security concerns this may raise, for now, i'd suggest using services vpn services such as Tailscale or Zerotier for routing to private networks remotely. Though it is possible to implement, it would require some prebuild configuration which is rather annoying.

**Comment by Vali-98** [comment]
Pre-release uploaded that should grant the use of user-defined SSL certs. UI on pre-release is a bit buggy.

Feel free to reopen the issue if it doesn't work.
