### ISSUE TITLE
Rwkv Support

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#83]
So it seems like rwkv support is broken and the app crashes once you try to load the gguf. I did some basic research and I think it's because this merge is missing: 
https://github.com/ggerganov/llama.cpp/pull/9428

**Comment by Vali-98** [comment]
This is known. At the moment RWKV has not been merged into cui-llama.rn due to llama.cpp reworking a lot of the sampler code, so I was waiting for that to settle before releasing a version with the latest llama.cpp. I'll see if I can release a small patch sometime this week.

**Comment by Vali-98** [comment]
Pre-release uploaded that should have the updated lcpp, granted I havent fully tested it. UI is buggy however!
