### ISSUE TITLE
Allow longer prompt

### ISSUE THREAD

**Issue by vYLQs6** [Vali-98/ChatterUI#84]
Despite enabling an 8K context window in ChatterUI, longer prompts are not being forwarded to the local API.

This issue suggests a potential limitation within ChatterUI's prompt handling, preventing it from utilizing the full 8K capacity. To resolve this, **adjusting the internal prompt length limit** within ChatterUI is crucial. Since my prompts fall well within the configured 8K context, they should be seamlessly transmitted to the API for processing.

**Comment by Vali-98** [comment]
Could you provide an example of a broken prompt? As far as I know, the internal length setup should work.

**Comment by Vali-98** [comment]
Note that for local models, it uses a separate context length setting when you first load the model in the API menu, not in the sampler settings.

**Comment by Vali-98** [comment]
Yep, I tested with 2k context length and it seems to work just fine.

However, I do have a possible reason for why your gens are far below the limit: https://github.com/Vali-98/ChatterUI/issues/60#issuecomment-2273651360

its possible that your Generated Length is too high, and its eating up all context space, as context is built as:

```
this.buildTextCompletionContext(localPreset.context_length - n_predict),
```
This is necessary as both context and generated tokens share that same max context length.
