### ISSUE TITLE
Tree view and interaction

### ISSUE THREAD

**Issue by llight3** [Vali-98/ChatterUI#85]
It would be great if one could go back to a previous message and choose or generate a dffrent response.

**Comment by Vali-98** [comment]
I think instead I could duplicate chats when needed, it would be slow but the current storage method just doesnt allow for easy tree methods.

**Comment by llight3** [comment]
I don't quite know what you mean but I think thats how koboldcpp's tree works it just resends the whole history once you ask for a responce on a divergent branch

**Comment by llight3** [comment]
Also I think you already are storing the branches to some extent because when I export the json I can see other responses under swipes and the selected one under swipe id

**Comment by Vali-98** [comment]
The issue I have is branch tracking, as I currently do not store how chat entries are linked or how they should be loaded if they do. The app's internal database very naively loads the chat in order of its order value. It lacks a proper single linked-list style reference to next nodes.

Chat duplication is a feature I do want to add anyways, and can somewhat serve this feature, albeit being somewhat cumbersome.

**Comment by Vali-98** [comment]
Release made: https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.0-beta3

Added chat cloning which can substitute for a tree structure for now.
