### ISSUE TITLE
TTS language bound to character

### ISSUE THREAD

**Issue by doncamillo0815** [Vali-98/ChatterUI#9]
A suggestion for improvement would be that the TTS language is bound to the character. Thus, a corresponding language is used for a multilingual AI.
For example, if an english character is used, that the english TTS language is used.

**Comment by Vali-98** [comment]
This will likely not be a feature, as some languages do not use common scripts. Plus this will depend entirely on the system level TTS available which may note exist for specific languages.

**Comment by GameOverFlowChart** [comment]
> This will likely not be a feature, as some languages do not use common scripts. Plus this will depend entirely on the system level TTS available which may note exist for specific languages.
> 
> Edit: After some consideration, I think this can be done in a sense, perhaps even tie characters to specific TTS voices. However this will probably be low priority, so I will keep this issue open.

Yes having the option for male or female voices for the characters would be useful if you already made characters part of the app.

**Comment by Vali-98** [comment]
I found that TTS providers make it somewhat difficult to consistently have this work. As such I do not think this can be added cleanly. Sorry!
