### ISSUE TITLE
Can the model be loaded automatically?

### ISSUE THREAD

**Issue by GeminiX369** [Vali-98/ChatterUI#90]
Sometimes when you open the app and start chatting, you forget to go to the API interface and click the load button, and this is very inconvenient. So I hope that after entering the chat message, if the local model is used and the model is not loaded, it will be automatically loaded, which will be much more convenient.

In addition, it would be better if you can customize the server address of the openAI interface. There are many third-party services that implement the same interface as openAI. I hope to use them in ChatterUI. Thanks.

**Comment by Vali-98** [comment]
Hey there, these features are already in the app:

> So I hope that after entering the chat message, if the local model is used and the model is not loaded

Open the side drawer > Settings (top right Gear button) > Enable `Load Local Model on Chat`

> customize the server address of the openAI interface

The Chat Completions endpoint is essentially just the OpenAI spec with customizable fields.

**Comment by GeminiX369** [comment]
> Hey there, these features are already in the app:
> 
> > So I hope that after entering the chat message, if the local model is used and the model is not loaded
> 
> Open the side drawer > Settings (top right Gear button) > Enable `Load Local Model on Chat`
> 
> > customize the server address of the openAI interface
> 
> The Chat Completions endpoint is essentially just the OpenAI spec with customizable fields.
> 
> If there are any problems with these features, feel free to reopen the issue.

I'm sorry, I completely missed the settings icon. Thank you for your help.
