### ISSUE TITLE
Auto identifying AArch64 SoC features

### ISSUE THREAD

**Issue by manuelpaulo** [Vali-98/ChatterUI#92]
For less geek users, default to Llama-3.2-1B-Instruct-GGUF, and auto select and download the best model:

For instance, Snapdragon X? Has i8mm? YES Has sve? NO -> select Q4_0_4_8.

Could also select a bigger model, if enough VRAM/RAM is found.

Of course, users were then free to modify it at will.

Just an ideia, and Thanks for this!

**Comment by Vali-98** [comment]
I likely won't add a downloader to the app, as it is somewhat complex to do. However, I do want to add an indicator for supported quantization levels:
![image](https://github.com/user-attachments/assets/9355b8c1-7654-40eb-a901-0c7857dd8ec7)

I'll leave picking the actual models down to the user.
