### ISSUE TITLE
Version mismatch in the beta releases

### ISSUE THREAD

**Issue by netroy** [Vali-98/ChatterUI#93]
Hi, I'm installing this via Obtainium, which in turn is downloading the APK from github releases.
The issue is that the version is hard-coded to `0.7.10` [here](https://github.com/Vali-98/ChatterUI/blob/master/app.config.js#L5), which makes Obtainium always think that the installed app is out of date.
The version shown in the app sidebar is also incorrect because of this.

If this is intentional, please free to close this issue. 
But if it's unintentional, and you'd like me to send a PR, please let me know 🙏🏽

**Comment by Vali-98** [comment]
Are you installing the pre-releases? If so, the version is intended to be inaccurate.

That said, I will consider properly signing the app with the correct beta versions.

**Comment by netroy** [comment]
> Are you installing the pre-releases

yeah. I have the prereleases flag enabled in Obtainium.


> I will consider properly signing the app

Thanks ❤️, but keeping the version in sync doesn't need to depend on the signing related work, right?

**Comment by Vali-98** [comment]
> Thanks ❤️, but keeping the version in sync doesn't need to depend on the signing related work, right?

Oh yeah, I just meant properly placing the correct version tag in the app.config.js

**Comment by KaKi87** [comment]
Hello,
I'm experiencing the same issue.
Thanks
