### ISSUE TITLE
Bugs with 0.8

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#96]
So I had finally time to check out the new gui. 
There are two problems, one is that the donate button is cut off.

![Screenshot_2024-10-25-01-35-20-15_46c75b0d777501bc756459feb21fe8e7](https://github.com/user-attachments/assets/3226cc2f-abd1-4212-af17-db240d6af30a)

The other is that the models menue opens an empty screen and pressing the back button closes (or crashes?) the app. 
![Screenshot_2024-10-25-01-35-35-24_46c75b0d777501bc756459feb21fe8e7](https://github.com/user-attachments/assets/87615ae7-0830-466c-9a17-5aa753f41b4c)

**Comment by Vali-98** [comment]
Hey there, which version did you update from?
