### ISSUE TITLE
OpenAI integration seems broken

### ISSUE THREAD

**Issue by ezruneko** [Vali-98/ChatterUI#99]
Hi

I love your app and its very useful. 

But the OpenAI integration seems broken. When you send any text doesn't sent in the api request.

I ve attached some pics with the evidences

![Screenshot_2024-10-25-20-26-28-497_com Vali98 ChatterUI](https://github.com/user-attachments/assets/773954e7-41af-4dc4-b63f-99ec9fa4ec00)

![Screenshot_2024-10-25-20-26-39-945_com Vali98 ChatterUI](https://github.com/user-attachments/assets/251711f6-b84f-4714-8127-c55cef9ec836)

![Screenshot_2024-10-25-20-24-38-068_com Vali98 ChatterUI](https://github.com/user-attachments/assets/1dc51bf5-21c7-4063-847f-f33f8d121615)
![Screenshot_2024-10-25-20-23-20-805_com Vali98 ChatterUI](https://github.com/user-attachments/assets/1ddd7226-924e-46ae-aa2d-86d6d2da17db)

**Comment by Vali-98** [comment]
How high did you set Generated Tokens? If set too high, it may cause messages to be truncated.

**Comment by ezruneko** [comment]
I've not changed any value. This is my configuration and i use the las versión 0.8.0:

![Screenshot_2024-10-27-09-31-06-364_com Vali98 ChatterUI](https://github.com/user-attachments/assets/e1465a44-5a1e-446e-bfeb-b7cc01e0c2ae)

In local mode with llama3, mixtral o Gemma no problem runs fine.

**Comment by ezruneko** [comment]
No problem. Thank you for your amazing support.

**Comment by Vali-98** [comment]
Should be fixed in: https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.1

Feel free to reopen this issue if this still occurs.
